# config/workflows/onboarding.yml - FICHIER COMPLET CORRIGÉ

id: onboarding
name: 'Configuration utilisateur'
description: 'Inscription et liaison avec contribuable DGI'
startStep: collect_name

steps:
  collect_name:
    type: input
    messageKey: 'workflows.onboarding.collect_name'
    validation:
      required: true
      minLength: 2
      maxLength: 100
    saveAs: user_name
    next: search_dgi

  search_dgi:
    type: service
    messageKey: 'workflows.onboarding.searching_dgi'
    service: 'dgi_scraper'
    method: 'rechercherParNom'
    params:
      nom: '{{user_name}}'
    saveAs: dgi_search_result
    onSuccess:
      - if: "service_result.type === 'unique'"
        then: confirm_single
      - if: "service_result.type === 'multiple'"
        then: select_multiple
      - if: "service_result.type === 'aucune'"
        then: complete_name_only
    onError: search_error

  confirm_single:
    type: menu
    messageKey: 'workflows.onboarding.confirm_single'
    options:
      - id: '1'
        labelKey: 'workflows.onboarding.option_yes_its_me'
        value: true
      - id: '2'
        labelKey: 'workflows.onboarding.option_no_retry'
        value: false
    saveAs: user_confirmation
    next:
      - if: 'user_confirmation === true'
        then: async_link_taxpayer
      - if: 'user_confirmation === false'
        then: collect_name

  select_multiple:
    type: menu
    messageKey: 'workflows.onboarding.select_multiple'
    saveAs: selected_taxpayer
    next: async_link_taxpayer

  async_link_taxpayer:
    type: service
    service: 'taxpayer_service'
    method: 'createAndLinkWithAsyncEnrichment'
    params:
      botUserId: '{{userId}}'
      taxpayerData: '{{selected_taxpayer}}'
    onSuccess: complete_with_taxpayer
    onError: link_error

  complete_with_taxpayer:
    type: message
    messageKey: 'workflows.onboarding.complete_with_taxpayer'

  complete_name_only:
    type: message
    messageKey: 'workflows.onboarding.complete_name_only'

  search_error:
    type: message
    messageKey: 'workflows.onboarding.search_error'
    next: collect_name

  link_error:
    type: message
    messageKey: 'workflows.onboarding.link_error'
    next: complete_name_only
