export const ErrorCodes = {
  // Authentification
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',

  // Autorisation
  PERM_INSUFFICIENT_PRIVILEGES: 'PERM_INSUFFICIENT_PRIVILEGES',
  PERM_ROLE_NOT_FOUND: 'PERM_ROLE_NOT_FOUND',
  PERM_PERMISSION_DENIED: 'PERM_PERMISSION_DENIED',

  // Validation
  VALID_EMAIL_REQUIRED: 'VALID_EMAIL_REQUIRED',
  VALID_EMAIL_INVALID: 'VALID_EMAIL_INVALID',
  VALID_EMAIL_EXISTS: 'VALID_EMAIL_EXISTS',
  VALID_PASSWORD_WEAK: 'VALID_PASSWORD_WEAK',
  VALID_ROLE_REQUIRED: 'VALID_ROLE_REQUIRED',
  VALID_INVALID_STATUS: 'VALID_INVALID_STATUS',

  // Ressources
  RESOURCE_USER_NOT_FOUND: 'RESOURCE_USER_NOT_FOUND',
  RESOURCE_ROLE_NOT_FOUND: 'RESOURCE_ROLE_NOT_FOUND',
  RESOURCE_CANNOT_DELETE_LAST_ADMIN: 'RESOURCE_CANNOT_DELETE_LAST_ADMIN',
  RESOURCE_CANNOT_DELETE_SELF: 'RESOURCE_CANNOT_DELETE_SELF',
  RESOURCE_ROLE_IN_USE: 'RESOURCE_ROLE_IN_USE',

  // Génériques
  GENERAL_SERVER_ERROR: 'GENERAL_SERVER_ERROR',
  GENERAL_NOT_FOUND: 'GENERAL_NOT_FOUND',
  GENERAL_VALIDATION_ERROR: 'GENERAL_VALIDATION_ERROR',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
